const levels = {
  command: {n:1, icon:'🤖', title:'Turn the Bot', alert:'The bot is facing east. The charging tile is north.', mission:'Which command must come first?', hint:'A quarter turn to the left changes east into north.', choices:[['MOVE FORWARD','move'],['TURN LEFT','good'],['PICK UP ITEM','pick']], digit:'8', next:'bug.html'},
  bug: {n:2, icon:'🐛', title:'Fix the Bug', alert:'The bot should warn us when its battery is low.', code:'if battery < 20\n  showWarning()', mission:'This Python-style code has one small mistake. Which fix is correct?', hint:'In Python, the condition line needs a punctuation mark before the next line.', choices:[['Add a colon after 20','good'],['Remove the brackets','brackets'],['Change battery into robot','robot']], digit:'3', next:'condition.html'},
  condition: {n:3, icon:'🛣️', title:'Choose the Route', alert:'The rain sensor has detected a wet outdoor path.', code:'IF pathIsWet\n  ...\nELSE\n  useOutdoorRoute()', mission:'Which line belongs where the dots are?', hint:'An IF statement tells the robot what to do when the condition is true.', choices:[['useIndoorRoute()','good'],['repeatRoute()','repeat'],['stopTheInternet()','internet']], digit:'1', next:'output.html'},
  output: {n:4, icon:'🔁', title:'Predict the Output', alert:'The bot has to move through three empty squares.', code:'repeat 3 times:\n  moveForward()', mission:'How many squares will the bot move?', hint:'The word “repeat” tells you how many times the command runs.', choices:[['1 square','one'],['3 squares','good'],['30 squares','thirty']], digit:'7', next:'sensor.html'},
  sensor: {n:5, icon:'🌡️', title:'Read the Sensor', alert:'The classroom is getting warm.', code:'temperature = 28\nif temperature > 26:\n  turnFanOn()', mission:'What will the program do?', hint:'28 is greater than 26, so the condition is true.', choices:[['Turn the fan on','good'],['Turn the fan off','off'],['Reset the robot','reset']], digit:'5', next:'finale.html'}
};
function progress(n){return `<div class="bar">${[1,2,3,4,5].map(x=>`<i class="${x<n?'done':x===n?'now':''}"></i>`).join('')}</div>`}
function frame(content,n=0){document.body.innerHTML=`<main class="phone"><header class="top"><strong>CODE RED</strong>${n?`<span class="tag">LEVEL ${n}/5</span>`:'<span class="tag">ENGLISH EDITION</span>'}</header>${n?progress(n):''}${content}<footer class="footer">TER AA · PROGRAMMING · OPEN DAY</footer></main>`}
function intro(){frame(`<section class="card"><p class="eyebrow">Emergency message · 09:00</p><h1>Save the<br>School Bot</h1><p class="lead">The delivery bot has stopped in the middle of the school. Solve five programming puzzles to reboot it.</p><div class="bot">🤖</div><div class="mission"><strong>Your mission:</strong> think like a programmer. Every correct answer gives you one number for the reboot code.</div><a class="button primary next" href="command.html">START MISSION →</a><div class="hint"><strong>Good to know:</strong> You do not need programming experience. Read carefully, try, and learn.</div></section>`)}
function stage(key){const x=levels[key];frame(`<section class="card"><p class="eyebrow">Mission ${x.n} · ${x.alert}</p><h1>${x.title}</h1><div class="bot">${x.icon}</div>${x.code?`<div class="code">${x.code}</div>`:''}<p class="mission">${x.mission}</p><div class="choices">${x.choices.map(([t,v])=>`<button data-answer="${v}">${t}</button>`).join('')}</div><div id="result" class="result" aria-live="polite"></div><div class="hint">💡 <strong>Hint:</strong> ${x.hint}</div></section>`,x.n);document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{const r=document.querySelector('#result');if(b.dataset.answer==='good'){localStorage.setItem('code-red-'+key,x.digit);r.className='result good';r.innerHTML=`Correct! Your reboot digit is <span class="digit">${x.digit}</span><a class="button primary next" href="${x.next}">NEXT PUZZLE →</a>`}else{r.className='result bad';r.textContent='Not quite. Read the clue and try again.'}}))}
function finale(){const digits=['command','bug','condition','output','sensor'].map(x=>localStorage.getItem('code-red-'+x)||'?');frame(`<section class="card"><p class="eyebrow">Final Mission · Reboot terminal</p><h1>Enter the<br>reboot code</h1><p class="lead">You solved the programming puzzles. Put the five digits in the correct order to restart the School Bot.</p><div class="bot">🔓</div><div class="mission">Collected digits: <strong>${digits.join(' · ')}</strong></div><div class="final">${[0,1,2,3,4].map((_,i)=>`<input aria-label="Reboot digit ${i+1}" inputmode="numeric" maxlength="1">`).join('')}</div><button id="open" class="primary">REBOOT THE BOT</button><div id="result" class="result" aria-live="polite"></div><div class="hint">Need a digit? Go back and solve that puzzle again.</div></section>`,5);const fields=[...document.querySelectorAll('input')];fields.forEach((f,i)=>f.addEventListener('input',()=>{if(f.value&&fields[i+1])fields[i+1].focus()}));document.querySelector('#open').addEventListener('click',()=>{const r=document.querySelector('#result'),value=fields.map(f=>f.value).join('');if(value==='83175'){r.className='result good';r.innerHTML='🎉 <strong>BOT REBOOTED!</strong> You saved the School Bot. Show this screen to a Ter AA student or teacher.'}else{r.className='result bad';r.textContent='Access denied. Check your digits and try again.'}})}
const page=document.body.dataset.page;if(page==='intro')intro();else if(page==='final')finale();else stage(page);
